version: "3.7"

services:
  postgres:
    build: ./docker/db/
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5444:5432

  ichiran:
    build: ./docker/ichiran/
    working_dir: /ichiran-web
    ports:
      - 2050:3000
    volumes:
      - ./:/ichiran-web
      - ./data:/root/quicklisp/local-projects/
    command: sh -c "npm i && npm start"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD

volumes:
  db-data:
